# -*- coding: utf-8 -*-
"""simple arth prog.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1eXLdhn-PGhOjgKCAtoBRd_jA5audPh
"""

a=int(input("enter 1st num"))
b=int(input("enter 2nd num"))
c=int(input("enter 3rd num"))
print(a+b,a-b,a/b,a*b)

